### ISSUE TITLE
Make Error: The source directory "path/to/llvm-reusable-enclaves" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by WonSivan** [OSUSecLab/Reusable-Enclaves#1]
It seems to be lack of a 'CMakeLists.txt' file in the root directory of this project. 

When i make a new directory 'build' and change director to it, after typing 'cmake ../' command, it failed with erros like "Make Error: The source directory "path/to/llvm-reusable-enclaves" does not appear to contain CMakeLists.txt.".

Looking forward to your reply, thank u!

**Comment by NSKernel** [comment]
Sorry should be "path/to/llvm-reusable-enclaves/llvm". Basically you just follow regular LLVM compilation process. I will update the README. Thanks.
